SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dtme].[udfGetTimeByZone](@UtcDate DATETIME2, @TimeZone VARCHAR(255))
RETURNS DATETIME2
WITH SCHEMABINDING
AS BEGIN
	RETURN (
		SELECT CAST(DATEADD(MINUTE, DATEPART(tz, @UtcDate AT TIME ZONE @TimeZone), @UtcDate AT TIME ZONE @TimeZone) AS DATETIME2)
	)
END
GO
