SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dtme].[udfGetTimeOnly](@DateTime DATETIME)
RETURNS DATETIME
AS
    BEGIN
        RETURN CONVERT(DATETIME, @DateTime - CONVERT(INT, @DateTime - 0.5))
    END
GO
