SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dtme].[udfGetDate]()
RETURNS DATETIME2
AS BEGIN
    -- Gets real datetime on On-Prem Server, and UTC on Azure.
    RETURN SYSDATETIME()
END
GO
