CREATE TABLE [dbo].[SQLManagerSubscriber]
(
[SUBSCRIBERNUM] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERSONCODE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENTCODE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTNAME] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRSTNAME] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MI] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR1] [nvarchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR2] [nvarchar] (55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HOMEPHONE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORKPHONE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [datetime] NULL,
[TERMINATION] [datetime] NULL,
[STATUS] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENDER] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARRIER] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCATION] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATETS] [datetime] NULL,
[DATEENTERED] [datetime] NULL,
[CARDDATE] [datetime] NULL,
[NUMCARDS] [float] NULL,
[TESTONLY] [float] NULL,
[INJDATE] [datetime] NULL,
[INJTYPE] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BROKER1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BROKER2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERNAME] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERADDR1] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERADDR2] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERCITY] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERSTATE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERZIP] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTER] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VENUESTATE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INJCAUSE] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLAIMID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COPAYBANKAMT] [decimal] (12, 2) NULL,
[COPAYBANKTYPE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHARGECARDNUM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHARGECARDEXP] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHARGECARDNAME] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAILADDRESS] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRANSITNUM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCOUNTNUM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARDSTATUS] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARDSTATUSDATE] [datetime] NULL,
[PCP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLEX2] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLEX3] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPCD] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NOUPDATE] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDEDBY] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MBRSINCE] [datetime] NULL,
[STR1_20] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_20] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_04] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_15] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_04] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_15] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RELCODE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ELIGOVERRIDE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR3_20] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_01] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_01] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_05] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_10] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FLEX1] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_02] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PREVIOUSCARDID] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ALTCARDID] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENROLLTYPE] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENROLLNABP] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTHBY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NONHIPPAID] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MFNAME] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARDPRINTDATE] [datetime] NULL,
[PCPPHONE] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LEGALREP] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTACT] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVATIONDATE] [datetime] NULL,
[PRIMARYPHARM] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIPHARMPHONE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIPHARMFAX] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BOOKLETDATE] [datetime] NULL,
[BOOKLETPRINTDATE] [datetime] NULL,
[COUNTRY] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR1_50] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERPHONE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLOYERFAX] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTERPHONE] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTERFAX] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BITFLAGS] [float] NULL,
[EXTELIGNEXT] [datetime] NULL,
[EXTELIGLAST] [datetime] NULL,
[FACILITY] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPFAX] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTEREMAIL] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILADDR1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILADDR2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILCITY] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILSTATE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILZIP] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARDAPC] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CARDBPC] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCPGROUP] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETHNICITY] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RACE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUERASSIGNEDMEMID] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUERASSIGNEDSUBID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIORINSCARRIERID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTPREMIUMPAIDDATE] [datetime] NULL,
[RELATIONSHIPDESC] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILFIRSTNAME] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILLASTNAME] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILPRIMARYPHONE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILSECONDARYPHONE] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CASEMANAGER] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJUSTEREXT] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MPRWC1] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MPRWC2] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MPRWC3] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPENTERDATE] [datetime] NULL,
[GPPERIODSEG] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR3_01] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_50] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR3_50] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGSPOKEN] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LANGPRINT] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEDAIDCODE] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENTPC] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPENDENCYRESTART] [datetime] NULL,
[GPTERMDATE] [datetime] NULL,
[STR1_90] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STR2_90] [nvarchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BENYRSTARTOVERRIDE] [datetime] NULL,
[DEPENDENCYLKBKDAYS] [decimal] (3, 0) NULL
) ON [PRIMARY]
GO
