CREATE TABLE [dbo].[Prescription]
(
[preid] [int] NOT NULL,
[preclaid] [int] NULL,
[preRxNum] [float] NULL,
[preDateSubmitted] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preDateFilled] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preLabelName] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prendc] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preqty] [float] NULL,
[preDaySupply] [float] NULL,
[pregeneric] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prePharmacyNABP] [nvarchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preAWP] [float] NULL,
[preAWPUnit] [float] NULL,
[preUsual] [decimal] (18, 0) NULL,
[prePrescriber] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prePayableAmt] [decimal] (18, 0) NULL,
[preBilledAmt] [decimal] (18, 0) NULL,
[preTransactionType] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preCompound] [float] NULL,
[preTran] [nvarchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preRefillDate] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preRefillNum] [smallint] NULL,
[preMONY] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preDAW] [smallint] NULL,
[preGPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preBillIngrCost] [float] NULL,
[preBillDispFee] [int] NULL,
[preBilledTax] [int] NULL,
[preBilledCopay] [int] NULL,
[prePayIngrCost] [int] NULL,
[prePayDispFee] [int] NULL,
[prePayTax] [int] NULL,
[preDEA] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[prePrescriberNPI] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preStrength] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preGPIGenName] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preTheraClass] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
