CREATE TABLE [dbo].[Tally]
(
[N] [int] NOT NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = ROW
)
GO
ALTER TABLE [dbo].[Tally] ADD CONSTRAINT [pkTally] PRIMARY KEY CLUSTERED  ([N]) WITH (FILLFACTOR=90, DATA_COMPRESSION = ROW) ON [PRIMARY]
GO
