CREATE TABLE [etl].[EnvisionStaging]
(
[RowID] [int] NOT NULL IDENTITY(1, 1),
[CarrierID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RelCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSN] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subgroup] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FillDate] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WrittenDate] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessDate] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessTime] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PharmacyNPI] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PharmacyName] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubmittedPrescriberID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AltPrescriberID] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RxNumber] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QTY] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DS] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FillNumber] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TranType] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DAW] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Compound] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherCoverageCode] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RxOrigin] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MPANumber] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarkScriptAs] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AuthNumber] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReversedAuth] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NDC] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GPI] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrugName] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MONY] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEAClass] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tier] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IngredCost] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DispFee] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesTax] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VaccineAdminFee] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberCostShareCopay] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GroupBillAmount] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeductibleAmount] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberOOP] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BenefitAmount] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCIND1] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCVALUE1] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCIND2] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCVALUE2] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCIND3] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCVALUE3] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCIND4] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCVALUE4] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCIND5] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SDCVALUE5] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO
ALTER TABLE [etl].[EnvisionStaging] ADD CONSTRAINT [pkEnvisionStaging] PRIMARY KEY CLUSTERED  ([RowID]) WITH (FILLFACTOR=90, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
